apiVersion: v1
kind: Service
metadata:
  name: product-service-app  # This is the internal DNS name for the service
spec:
  selector:
    app: product-service      # This should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 8080              # The port that other services will use to connect
      targetPort: 8080        # The port exposed by the container (should match the container port)
  type: ClusterIP              # Exposes the service only within the clus